In [25]:
import pandas as pd
import json

In [2]:
df = pd.read_csv('reviews.csv')
df.head()

,id,asins,brand,categories,colors,dateAdded,dateUpdated,dimension,ean,keys,...,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.userCity,reviews.userProvince,reviews.username,sizes,upc,weight
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",NaN,NaN,Cristina M,NaN,NaN,205 grams
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,NaN,NaN,Ricky,NaN,NaN,205 grams
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,NaN,NaN,Tedd Gardiner,NaN,NaN,205 grams
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,NaN,NaN,Dougal,NaN,NaN,205 grams
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",NaN,2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,169 mm x 117 mm x 9.1 mm,NaN,kindlepaperwhite/b00qjdu3ky,...,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,NaN,NaN,Miljan David Tanic,NaN,NaN,205 grams

In [6]:
df.nunique()

id                        66
asins                     54
brand                      2
categories                19
colors                     3
dateAdded                 50
dateUpdated               42
dimension                  2
ean                        2
keys                      66
manufacturer               2
manufacturerNumber         6
name                      62
prices                    66
reviews.date             382
reviews.doRecommend        2
reviews.numHelpful       182
reviews.rating             5
reviews.sourceURLs       499
reviews.text            1048
reviews.title           1270
reviews.userCity           0
reviews.userProvince       0
reviews.username         949
sizes                      0
upc                        2
weight                     9
dtype: int64

In [12]:
# check which cols to drop

cols = [
    'brand',
    'colors',
    'dimension',
    'ean',
    'manufacturer',
    'manufacturerNumber',
    'upc',
    'weight'
]

for col in cols:
    print(col)
    print(df[col].unique())
    print(df[df[col].notna()].shape[0])
    print(df.groupby(col)['id'].nunique())
    print('\n')

brand
['Amazon' 'Moshi']
1597
brand
Amazon    65
Moshi      1
Name: id, dtype: int64


colors
[nan 'GB' 'Black' 'Clear']
774
colors
Black    2
Clear    1
GB       1
Name: id, dtype: int64


dimension
['169 mm x 117 mm x 9.1 mm' nan '4.8 in x 6.6 in x 3.2 in']
565
dimension
169 mm x 117 mm x 9.1 mm    1
4.8 in x 6.6 in x 3.2 in    1
Name: id, dtype: int64


ean
[        nan 8.48719e+11 8.41667e+11]
898
ean
8.416670e+11    2
8.487190e+11    3
Name: id, dtype: int64


manufacturer
['Amazon' nan 'AMDSI']
965
manufacturer
AMDSI     1
Amazon    7
Name: id, dtype: int64


manufacturerNumber
[nan 'D01101' '8.48719E+11' 'B01BH83OOM' 'KA416Y' 'CV98LM' 'DR49WK']
902
manufacturerNumber
8.48719E+11    1
B01BH83OOM     1
CV98LM         1
D01101         1
DR49WK         1
KA416Y         1
Name: id, dtype: int64


upc
[        nan 8.48719e+11 8.41667e+11]
898
upc
8.416670e+11    2
8.487190e+11    3
Name: id, dtype: int64


weight
['205 grams' '1.1 pounds' nan '1.6 ounces' '1.75 lbs' '0.8 ounces'
 '4 ounces' '5 ounces' '4.6 ounces' '2.4 ounces']
686
weight
0.8 ounces    1
1.1 pounds    1
1.6 ounces    1
1.75 lbs      1
2.4 ounces    1
205 grams     1
4 ounces      2
4.6 ounces    1
5 ounces      1
Name: id, dtype: int64

In [13]:
# drop cols

cols_to_drop = [
    'colors',
    'dimension',
    'ean',
    'manufacturer',
    'manufacturerNumber',
    'upc',
    'weight',
    'reviews.userCity',
    'reviews.userProvince',
    'sizes'
]

df = df.drop(columns=cols_to_drop)
df.head()

,id,asins,brand,categories,dateAdded,dateUpdated,keys,name,prices,reviews.date,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.username
0,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,kindlepaperwhite/b00qjdu3ky,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2015-08-08T00:00:00.000Z,NaN,139.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",Cristina M
1,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,kindlepaperwhite/b00qjdu3ky,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2015-09-01T00:00:00.000Z,NaN,126.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,Ricky
2,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,kindlepaperwhite/b00qjdu3ky,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2015-07-20T00:00:00.000Z,NaN,69.0,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,Tedd Gardiner
3,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,kindlepaperwhite/b00qjdu3ky,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2017-06-16T00:00:00.000Z,NaN,2.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,Dougal
4,AVpe7AsMilAPnD_xQ78G,B00QJDU3KY,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,kindlepaperwhite/b00qjdu3ky,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2016-08-11T00:00:00.000Z,NaN,17.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,Miljan David Tanic

In [15]:
# drop redundant cols
df = df.drop(columns=['asins', 'keys', 'reviews.sourceURLs'])
df.head()

,id,brand,categories,dateAdded,dateUpdated,name,prices,reviews.date,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.sourceURLs,reviews.text,reviews.title,reviews.username
0,AVpe7AsMilAPnD_xQ78G,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2015-08-08T00:00:00.000Z,NaN,139.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",Cristina M
1,AVpe7AsMilAPnD_xQ78G,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2015-09-01T00:00:00.000Z,NaN,126.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,Allow me to preface this with a little history...,One Simply Could Not Ask For More,Ricky
2,AVpe7AsMilAPnD_xQ78G,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2015-07-20T00:00:00.000Z,NaN,69.0,4.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,Tedd Gardiner
3,AVpe7AsMilAPnD_xQ78G,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2017-06-16T00:00:00.000Z,NaN,2.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I bought one of the first Paperwhites and have...,Love / Hate relationship,Dougal
4,AVpe7AsMilAPnD_xQ78G,Amazon,"Amazon Devices,mazon.co.uk",2016-03-08T20:21:53Z,2017-07-18T23:52:58Z,Kindle Paperwhite,"[{""amountMax"":139.99,""amountMin"":139.99,""curre...",2016-08-11T00:00:00.000Z,NaN,17.0,5.0,https://www.amazon.com/Kindle-Paperwhite-High-...,I have to say upfront - I don't like coroporat...,I LOVE IT,Miljan David Tanic

In [18]:
df.categories.unique().tolist()

['Amazon Devices,mazon.co.uk',
 'Kindle Store,Amazon Devices,Electronics',
 'Categories,Amazon Devices,Streaming Media Players',
 'Amazon Devices',
 'Categories,Amazon Devices,Electronics Features,Streaming Media Players,Consumer Electronics,See more Amazon Fire TV Digital HD Media Streamer (Late...',
 'Amazon Devices & Accessories,Amazon Device Accessories,Power Adapters & Cables,Kindle Store,Kindle E-Reader Accessories,Kindle Paperwhite Accessories',
 'Amazon Devices,Kindle Store',
 'Electronics,Amazon Devices',
 'Amazon Devices,Kindle Accessories',
 'Amazon Devices,Electronics,Kindle Store',
 'Amazon Devices,Electronics,Kindle Store,Amazon Echo',
 'Amazon Devices,Kindle Store,Kindle Accessories',
 'Amazon Devices,Kindle Store,buy a kindle',
 'Amazon Devices,Home,Smart Home & Connected Living,Smart Hubs & Wireless Routers,Smart Hubs,Home Improvement,Home Safety & Security,Alarms & Sensors,Home Security,Amazon Echo,Home, Garage & Office,Smart Home,Voice Assistants,Amazon Tap,Electronics Features,TVs & Electronics,Portable Audio & Electronics,MP3 Player Accessories,Home Theater & Audio,Speakers,Featured Brands,Electronics,Kindle Store,Frys,Electronic Components,Home Automation,Electronics, Tech Toys, Movies, Music,Audio,Bluetooth Speakers',
 'Cell Phones & Accessories,Accessories,Screen Protectors,Cell,Amazon Devices,Electronics',
 'Amazon Devices & Accessories,Amazon Device Accessories,Controllers & Remote Controls,Kindle Store,Amazon Echo Accessories,Remote Controls',
 'Amazon Devices & Accessories,Amazon Device Accessories,Kindle Store,Kindle E-Reader Accessories,Kindle Oasis Accessories',
 'Amazon Devices,Corded Headsets,Electronics Features,Electronics,Audio,Headphones,Kindle Store,Kindle Accessories',
 'Amazon Devices & Accessories,Amazon Device Accessories,Controllers & Remote Controls,Kindle Store,Fire TV Accessories,Controllers & Remotes,Controllers']

In [28]:
df.iloc[0].prices

'[{"amountMax":139.99,"amountMin":139.99,"currency":"USD","dateAdded":"2017-07-18T23:52:58Z","dateSeen":["2017-07-15T18:10:23.807Z","2016-03-16T00:00:00Z"],"isSale":"false","merchant":"Amazon.com","shipping":"FREE Shipping.","sourceURLs":["https://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built/dp/B00QJDU3KY/ref=lp_6669702011_1_7/132-1677641-8459202?s=amazon-devices&ie=UTF8&qid=1498832761&sr=1-7","http://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built-/dp/B00QJDU3KY"]},{"amountMax":119.99,"amountMin":119.99,"condition":"new","currency":"EUR","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2016-01-29T00:00:00Z"],"isSale":"false","merchant":"Amazon EU Sarl","shipping":"free","sourceURLs":["http://www.amazon.co.uk/Kindle-Paperwhite-Resolution-Display-Built-/dp/B00QJDU3KY"]},{"amountMax":139.99,"amountMin":139.99,"condition":"new","currency":"CAD","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2016-01-11T00:00:00Z"],"isSale":"false","merchant":"Amazon","shipping":"free","sourceURLs":["http://www.amazon.ca/dp/B00QJDU3KY"]},{"amountMax":119.99,"amountMin":119.99,"currency":"USD","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2016-03-12T00:00:00Z"],"isSale":"true","merchant":"Amazon.com","sourceURLs":["http://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built-/dp/B00QJDU3KY"]},{"amountMax":119.99,"amountMin":119.99,"condition":"new","currency":"EUR","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2015-11-15T00:00:00Z"],"isSale":"false","merchant":"Amazon","shipping":"free","sourceURLs":["http://www.amazon.co.uk/All-New-Kindle-Paperwhite-Resolution-Display/dp/B00QJDU3KY"]},{"amountMax":17.99,"amountMin":17.99,"condition":"new","currency":"EUR","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2016-01-29T00:00:00Z"],"isSale":"false","merchant":"Amazon EU Sarl","shipping":"free","sourceURLs":["http://www.amazon.co.uk/Kindle-Paperwhite-Resolution-Display-Built-/dp/B00QJDU3KY"]},{"amountMax":17.99,"amountMin":17.99,"condition":"new","currency":"EUR","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2015-11-15T00:00:00Z"],"isSale":"false","merchant":"Amazon","shipping":"free","sourceURLs":["http://www.amazon.co.uk/All-New-Kindle-Paperwhite-Resolution-Display/dp/B00QJDU3KY"]},{"amountMax":139.00,"amountMin":139.00,"condition":"new","currency":"CAD","dateAdded":"2016-03-08T20:21:53Z","dateSeen":["2015-07-06T05:00:00Z"],"isSale":"false","merchant":"Amazon.ca","shipping":"free","sourceURLs":["http://www.amazon.ca/dp/B00QJDU3KY"]}]'

In [29]:
json.loads(df.iloc[0].prices)

[{'amountMax': 139.99,
  'amountMin': 139.99,
  'currency': 'USD',
  'dateAdded': '2017-07-18T23:52:58Z',
  'dateSeen': ['2017-07-15T18:10:23.807Z', '2016-03-16T00:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon.com',
  'shipping': 'FREE Shipping.',
  'sourceURLs': ['https://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built/dp/B00QJDU3KY/ref=lp_6669702011_1_7/132-1677641-8459202?s=amazon-devices&ie=UTF8&qid=1498832761&sr=1-7',
   'http://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built-/dp/B00QJDU3KY']},
 {'amountMax': 119.99,
  'amountMin': 119.99,
  'condition': 'new',
  'currency': 'EUR',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2016-01-29T00:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon EU Sarl',
  'shipping': 'free',
  'sourceURLs': ['http://www.amazon.co.uk/Kindle-Paperwhite-Resolution-Display-Built-/dp/B00QJDU3KY']},
 {'amountMax': 139.99,
  'amountMin': 139.99,
  'condition': 'new',
  'currency': 'CAD',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2016-01-11T00:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon',
  'shipping': 'free',
  'sourceURLs': ['http://www.amazon.ca/dp/B00QJDU3KY']},
 {'amountMax': 119.99,
  'amountMin': 119.99,
  'currency': 'USD',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2016-03-12T00:00:00Z'],
  'isSale': 'true',
  'merchant': 'Amazon.com',
  'sourceURLs': ['http://www.amazon.com/Kindle-Paperwhite-High-Resolution-Display-Built-/dp/B00QJDU3KY']},
 {'amountMax': 119.99,
  'amountMin': 119.99,
  'condition': 'new',
  'currency': 'EUR',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2015-11-15T00:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon',
  'shipping': 'free',
  'sourceURLs': ['http://www.amazon.co.uk/All-New-Kindle-Paperwhite-Resolution-Display/dp/B00QJDU3KY']},
 {'amountMax': 17.99,
  'amountMin': 17.99,
  'condition': 'new',
  'currency': 'EUR',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2016-01-29T00:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon EU Sarl',
  'shipping': 'free',
  'sourceURLs': ['http://www.amazon.co.uk/Kindle-Paperwhite-Resolution-Display-Built-/dp/B00QJDU3KY']},
 {'amountMax': 17.99,
  'amountMin': 17.99,
  'condition': 'new',
  'currency': 'EUR',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2015-11-15T00:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon',
  'shipping': 'free',
  'sourceURLs': ['http://www.amazon.co.uk/All-New-Kindle-Paperwhite-Resolution-Display/dp/B00QJDU3KY']},
 {'amountMax': 139.0,
  'amountMin': 139.0,
  'condition': 'new',
  'currency': 'CAD',
  'dateAdded': '2016-03-08T20:21:53Z',
  'dateSeen': ['2015-07-06T05:00:00Z'],
  'isSale': 'false',
  'merchant': 'Amazon.ca',
  'shipping': 'free',
  'sourceURLs': ['http://www.amazon.ca/dp/B00QJDU3KY']}]

In [30]:
pd.DataFrame(json.loads(df.iloc[0].prices))

,amountMax,amountMin,currency,dateAdded,dateSeen,isSale,merchant,shipping,sourceURLs,condition
0,139.99,139.99,USD,2017-07-18T23:52:58Z,"[2017-07-15T18:10:23.807Z, 2016-03-16T00:00:00Z]",false,Amazon.com,FREE Shipping.,[https://www.amazon.com/Kindle-Paperwhite-High...,NaN
1,119.99,119.99,EUR,2016-03-08T20:21:53Z,[2016-01-29T00:00:00Z],false,Amazon EU Sarl,free,[http://www.amazon.co.uk/Kindle-Paperwhite-Res...,new
2,139.99,139.99,CAD,2016-03-08T20:21:53Z,[2016-01-11T00:00:00Z],false,Amazon,free,[http://www.amazon.ca/dp/B00QJDU3KY],new
3,119.99,119.99,USD,2016-03-08T20:21:53Z,[2016-03-12T00:00:00Z],true,Amazon.com,NaN,[http://www.amazon.com/Kindle-Paperwhite-High-...,NaN
4,119.99,119.99,EUR,2016-03-08T20:21:53Z,[2015-11-15T00:00:00Z],false,Amazon,free,[http://www.amazon.co.uk/All-New-Kindle-Paperw...,new
5,17.99,17.99,EUR,2016-03-08T20:21:53Z,[2016-01-29T00:00:00Z],false,Amazon EU Sarl,free,[http://www.amazon.co.uk/Kindle-Paperwhite-Res...,new
6,17.99,17.99,EUR,2016-03-08T20:21:53Z,[2015-11-15T00:00:00Z],false,Amazon,free,[http://www.amazon.co.uk/All-New-Kindle-Paperw...,new
7,139.00,139.00,CAD,2016-03-08T20:21:53Z,[2015-07-06T05:00:00Z],false,Amazon.ca,free,[http://www.amazon.ca/dp/B00QJDU3KY],new

In [31]:
# count price difference between amount max and amount min
count = 0
nonzero_diff = 0
for i, row in df.iterrows():
    prices = json.loads(df.iloc[i].prices)
    for price in prices:
        diff = price['amountMax'] - price['amountMin']
        if diff != 0:
            nonzero_diff += 1
        count += 1
print(nonzero_diff)
print(count)

542
11995

In [36]:
df.groupby('id')['prices'].nunique()

id
AV000tWuGV-KLJ3ac2-b    1
AV00l7jV-jtxr-f30lnX    1
AV00lzP7GV-KLJ3ac0uk    1
AV00lzd5GV-KLJ3ac0ul    1
AV1Nik13-jtxr-f31AFO    1
                       ..
AVzRloqLGV-KLJ3aavBd    1
AVzRlpC2vKc47QAVd5FA    1
AVzRlpC8glJLPUi8FbQA    1
AVzRlpElvKc47QAVd5FB    1
AVzRlqklGV-KLJ3aavB0    1
Name: prices, Length: 66, dtype: int64

In [38]:
# create price dataframe
dfp = df.groupby('id')['prices'].first().reset_index()
dfp.head()

                     id                                             prices
0  AV000tWuGV-KLJ3ac2-b  [{"amountMax":229.99,"amountMin":229.99,"curre...
1  AV00l7jV-jtxr-f30lnX  [{"amountMax":19.99,"amountMin":19.99,"currenc...
2  AV00lzP7GV-KLJ3ac0uk  [{"amountMax":14.99,"amountMin":14.99,"currenc...
3  AV00lzd5GV-KLJ3ac0ul  [{"amountMax":49.99,"amountMin":49.99,"currenc...
4  AV1Nik13-jtxr-f31AFO  [{"amountMax":79.99,"amountMin":79.99,"currenc...

In [54]:
price_data = []

for i, row in dfp.iterrows():
    pid = row.id
    brand = df[df.id==pid]['brand'].iloc[0]
    categories = df[df.id==pid]['categories'].iloc[0]
    dateAdded = df[df.id==pid]['dateAdded'].iloc[0]
    dateUpdated = df[df.id==pid]['dateUpdated'].iloc[0]
    name = df[df.id==pid]['name'].iloc[0]
    prices = json.loads(dfp.iloc[i].prices)
    for price in prices:
        price_data.append({
            'id': row.id,
            'brand': brand,
            'categories': categories,
            'dateAdded': dateAdded,
            'dateUpdated': dateUpdated,
            'name': name,
            'currency': price.get('currency', pd.NA),
            'amount': price.get('amountMax', pd.NA),
            'date': price.get('dateSeen', pd.NA),
            'isSale': price.get('isSale', pd.NA),
            'merchant': price.get('merchant', pd.NA),
            'shipping': price.get('shipping', pd.NA),
            'condition': price.get('condition', pd.NA),
        })
        
dfprice = pd.DataFrame(price_data)
dfprice.head()

,id,brand,categories,dateAdded,dateUpdated,name,currency,amount,date,isSale,merchant,shipping,condition
0,AV000tWuGV-KLJ3ac2-b,Amazon,Amazon Devices,2017-07-12T03:23:38Z,2017-07-25T02:04:06Z,Echo Show - Black,USD,229.99,"[2017-07-21T23:11:11.925Z, 2017-07-21T23:06:16...",false,Amazon.com,FREE Shipping.,<NA>
1,AV00l7jV-jtxr-f30lnX,Amazon,Amazon Devices,2017-07-12T02:19:04Z,2017-08-13T08:29:10Z,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,USD,19.99,"[2017-07-26T00:00:12.394Z, 2017-07-25T17:32:08...",false,Amazon.com,FREE Shipping on orders over USD 25.00,<NA>
2,AV00lzP7GV-KLJ3ac0uk,Amazon,Amazon Devices,2017-07-12T02:18:30Z,2017-08-13T08:28:52Z,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,USD,14.99,"[2017-07-25T23:52:21.319Z, 2017-07-25T23:44:35...",false,Amazon.com,FREE Shipping on orders over USD 25.00,<NA>
3,AV00lzP7GV-KLJ3ac0uk,Amazon,Amazon Devices,2017-07-12T02:18:30Z,2017-08-13T08:28:52Z,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,USD,9.99,"[2017-07-25T23:52:21.319Z, 2017-07-25T23:44:35...",true,Amazon.com,FREE Shipping on orders over USD 25.00,<NA>
4,AV00lzd5GV-KLJ3ac0ul,Amazon,Amazon Devices,2017-07-12T02:18:31Z,2017-07-18T23:46:14Z,All-New Amazon Fire TV Game Controller,USD,49.99,"[2017-06-30T15:54:25.350Z, 2017-06-30T15:23:41...",false,easy-to-open packaging,FREE Shipping.,<NA>

In [55]:
dfprice['date'] = [x[0] for x in dfprice['date']]
dfprice.head()

,id,brand,categories,dateAdded,dateUpdated,name,currency,amount,date,isSale,merchant,shipping,condition
0,AV000tWuGV-KLJ3ac2-b,Amazon,Amazon Devices,2017-07-12T03:23:38Z,2017-07-25T02:04:06Z,Echo Show - Black,USD,229.99,2017-07-21T23:11:11.925Z,false,Amazon.com,FREE Shipping.,<NA>
1,AV00l7jV-jtxr-f30lnX,Amazon,Amazon Devices,2017-07-12T02:19:04Z,2017-08-13T08:29:10Z,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,USD,19.99,2017-07-26T00:00:12.394Z,false,Amazon.com,FREE Shipping on orders over USD 25.00,<NA>
2,AV00lzP7GV-KLJ3ac0uk,Amazon,Amazon Devices,2017-07-12T02:18:30Z,2017-08-13T08:28:52Z,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,USD,14.99,2017-07-25T23:52:21.319Z,false,Amazon.com,FREE Shipping on orders over USD 25.00,<NA>
3,AV00lzP7GV-KLJ3ac0uk,Amazon,Amazon Devices,2017-07-12T02:18:30Z,2017-08-13T08:28:52Z,Amazon Echo Dot Case (fits Echo Dot 2nd Genera...,USD,9.99,2017-07-25T23:52:21.319Z,true,Amazon.com,FREE Shipping on orders over USD 25.00,<NA>
4,AV00lzd5GV-KLJ3ac0ul,Amazon,Amazon Devices,2017-07-12T02:18:31Z,2017-07-18T23:46:14Z,All-New Amazon Fire TV Game Controller,USD,49.99,2017-06-30T15:54:25.350Z,false,easy-to-open packaging,FREE Shipping.,<NA>

In [50]:
dfprice.groupby('id')['currency'].nunique()

id
AV000tWuGV-KLJ3ac2-b    1
AV00l7jV-jtxr-f30lnX    1
AV00lzP7GV-KLJ3ac0uk    1
AV00lzd5GV-KLJ3ac0ul    1
AV1Nik13-jtxr-f31AFO    1
                       ..
AVzRloqLGV-KLJ3aavBd    1
AVzRlpC2vKc47QAVd5FA    1
AVzRlpC8glJLPUi8FbQA    1
AVzRlpElvKc47QAVd5FB    1
AVzRlqklGV-KLJ3aavB0    1
Name: currency, Length: 66, dtype: int64

In [56]:
dfprice.to_csv('prices_clean.csv', index=False)

In [59]:
df = df.drop(columns=['brand', 'categories', 'dateAdded', 'dateUpdated', 'name', 'prices'])
df.head()

,id,reviews.date,reviews.doRecommend,reviews.numHelpful,reviews.rating,reviews.text,reviews.title,reviews.username
0,AVpe7AsMilAPnD_xQ78G,2015-08-08T00:00:00.000Z,NaN,139.0,5.0,I initially had trouble deciding between the p...,"Paperwhite voyage, no regrets!",Cristina M
1,AVpe7AsMilAPnD_xQ78G,2015-09-01T00:00:00.000Z,NaN,126.0,5.0,Allow me to preface this with a little history...,One Simply Could Not Ask For More,Ricky
2,AVpe7AsMilAPnD_xQ78G,2015-07-20T00:00:00.000Z,NaN,69.0,4.0,I am enjoying it so far. Great for reading. Ha...,Great for those that just want an e-reader,Tedd Gardiner
3,AVpe7AsMilAPnD_xQ78G,2017-06-16T00:00:00.000Z,NaN,2.0,5.0,I bought one of the first Paperwhites and have...,Love / Hate relationship,Dougal
4,AVpe7AsMilAPnD_xQ78G,2016-08-11T00:00:00.000Z,NaN,17.0,5.0,I have to say upfront - I don't like coroporat...,I LOVE IT,Miljan David Tanic

In [60]:
df.to_csv('reviews_clean.csv', index=False)